### ISSUE TITLE
Morning Session: Peer-to-peer-code review

### ISSUE THREAD

**Issue by Ayokunnumi1** [AlselwiAisha/Leaderboard#4]
Welldone Aisha! You have done a great job in interacting with the leaderboard API, we are able to add new names and scores to the score table. However, kindly add a simple styling in the score box; an overflow-y: scroll to improve the user experience.

**Comment by Al-Amin-Khan-Shakil** [comment]
Absolutely great work! I will add something with the overflow that it would be better if you give a height to the score box.

**Comment by AlselwiAisha** [comment]
Thank you so much, I will fix that 👍

**Comment by AlselwiAisha** [comment]
Thanks
